### ISSUE TITLE
superscript

### ISSUE THREAD

**Issue by mark-gluzman** [spnbook/spnbook.github.io#4]
**Location**
Please provide the 
1. found on 1/29/2020
3. page 234
4. line 3 from the top

Missed superscript z on E:

$\frac{1}{|z|}E(|z|t, w) -- > \frac{1}{|z|}E^**z**(|z|t, w)$

**Comment by spnbook** [comment]
E actually does not depend on the initial state; this is a feature in discrete-time slotted model. To alert the readers that E does not depend on Z, on page 233, we have added a half sentence that ", but E does not".
